import { MenuInfo } from './menu-info';

export const ROUTES: MenuInfo[] = [
  {
    path: 'dashboard',
    title: 'DASHBOARD',
    icon: 'monitor',
    class: '',
    submenu: [],
    hasClaims: ['View_Dashboard'],
  },
  {
    path: '',
    title: 'ASSIGNED_DOCUMENT',
    icon: 'share',
    class: 'menu-toggle',
    submenu: [
      {
        path: 'assign/list-view',
        title: 'DOCUMENT_VIEW',
        icon: 'email',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [],
      },
      {
        path: 'assign/folder-view',
        title: 'FOLDER_VIEW',
        icon: 'folder_open',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [],
      },
    ],
    hasClaims: [],
  },
  {
    path: 'documents',
    title: 'ALL_DOCUMENT',
    icon: 'layers',
    class: 'menu-toggle',
    submenu: [
      {
        path: 'documents/list-view',
        title: 'DOCUMENT_VIEW',
        icon: 'email',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [],
      },
      {
        path: 'documents/folder-view',
        title: 'FOLDER_VIEW',
        icon: 'folder_open',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [],
      },
    ],
    hasClaims: ['ALL_View_Documents'],
  },
  {
    path: 'categories',
    title: 'DOCUMENT_CATEGORIES',
    icon: 'folder',
    class: '',
    submenu: [],
    hasClaims: ['View_Categories'],
  },
  {
    path: 'documents/deep-search',
    title: 'DEEP_SEARCH',
    icon: 'manage_search',
    class: '',
    submenu: [],
    hasClaims: ['deep_search'],
  },
  {
    path: '',
    title: 'AI_DOCUMENTS',
    icon: 'archive',
    class: 'menu-toggle',
    hasClaims: [
      'View_AI_Document_Generator',
      'AI_Document_Generator',
      'View_Prompt_Templates'
    ],
    submenu: [
      {
        path: 'ai-document-generator',
        title: 'AI_DOCUMENT_GENERATOR',
        icon: 'cpu',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['AI_Document_Generator']
      },
      {
        path: 'ai-document-generator-list',
        title: 'AI_DOCUMENT_GENERATOR_LIST',
        icon: 'cpu',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['View_AI_Document_Generator']
      },
      {
        path: 'aiprompttemplate',
        title: 'AI_PROMPT_TEMPLATES',
        icon: 'smart_toy',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['View_Prompt_Templates']
      }
    ],
  },
  {
    path: 'documents/ocr_content_extractor',
    title: 'OCR_CONTENT_EXTRACTOR',
    icon: 'search',
    class: '',
    submenu: [],
    hasClaims: ['ocr_content_extractor'],
  },
  {
    path: 'bulk-document-upload',
    title: 'BULK_DOCUMENT_UPLOAD',
    icon: 'upload',
    class: '',
    submenu: [],
    hasClaims: ['bulk_document_uploads'],
  },
  {
    path: 'file-request',
    title: 'FILE_REQUEST_LINK',
    icon: 'request_page',
    class: '',
    submenu: [],
    hasClaims: ['view_file_request'],
  },
  {
    path: 'current-workflow',
    title: 'ASSIGNED_WORKFLOWS',
    icon: 'assignment_ind',
    class: '',
    submenu: [],
    hasClaims: ['current_workflow'],
  },
  {
    path: '',
    title: 'WORKFLOWS',
    icon: 'repeat',
    class: 'menu-toggle',
    hasClaims: [
      'view_workflow_settings',
      'add_workflow_settings',
      'edit_workflow_settings',
      'delete_workflow_settings',
      'workflows',
      'workflow_logs',
    ],
    submenu: [
      {
        path: 'workflow-settings',
        title: 'WORKFLOW_SETTINGS',
        icon: 'key',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [
          'view_workflow_settings',
          'add_workflow_settings',
          'edit_workflow_settings',
          'delete_workflow_settings',
        ],
      },
      {
        path: 'workflows',
        title: 'ALL_WORKFLOWS',
        icon: 'view_list',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['workflows'],
      },
      {

        path: 'request_document_through_workflow',
        title: 'REQUEST_DOCUMENT_THROUGH_WORKFLOW',
        icon: 'description',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [],
      },
      {
        path: 'workflowlogs',
        title: 'WORKFLOW_LOGS',
        icon: 'history',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['workflow_logs'],
      },
    ],
  },
  {
    path: 'reminders',
    title: 'REMINDER',
    icon: 'schedule',
    class: '',
    submenu: [],
    hasClaims: ['view_reminders'],
  },
  {
    path: 'document-audit-trails',
    title: 'DOCUMENTS_AUDIT_TRAIL',
    icon: 'gavel',
    class: '',
    submenu: [],
    hasClaims: ['view_document_audit_trail'],
  },
  {
    path: 'recent-activity',
    title: 'RECENT_ACTIVITY',
    icon: 'refresh',
    class: '',
    submenu: [],
    hasClaims: [],
  },
  {
    path: '',
    title: 'ARCHIVE',
    icon: 'archive',
    class: 'menu-toggle',
    hasClaims: [],
    submenu: [
      {
        path: 'archive-documents',
        title: 'DOCUMENTS',
        icon: 'insert_drive_file',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [],
      },
      {
        path: 'archive-folders',
        title: 'FOLDERS',
        icon: 'folder',
        class: 'ml-menu',
        submenu: [],
        hasClaims: [],
      },
      {
        path: 'archive-retention-period',
        title: 'ARCHIVE_RETENTION_PERIOD',
        icon: 'access_time',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['Manage_Archive_Retention_Period'],
      },
    ],
  },

  {
    path: 'document-status',
    title: 'DOCUMENT_STATUS',
    icon: 'check_circle',
    class: '',
    submenu: [],
    hasClaims: ['Manage_Document_Status'],
  },
  {
    path: 'client',
    title: 'CLIENTS',
    icon: 'account_circle',
    class: '',
    submenu: [],
    hasClaims: ['view_clients'],
  },
  {
    path: 'roles',
    title: 'ROLES',
    icon: 'shield',
    class: '',
    submenu: [],
    hasClaims: ['view_roles'],
  },
  {
    path: 'users',
    title: 'USERS',
    icon: 'group',
    class: '',
    submenu: [],
    hasClaims: ['view_users'],
  },
  {
    path: 'roles/users',
    title: 'ROLE_USER',
    icon: 'groups',
    class: '',
    submenu: [],
    hasClaims: ['user_role'],
  },

  {
    path: '',
    title: 'SETTINGS',
    icon: 'settings',
    class: 'menu-toggle',
    hasClaims: [
      'smtp_settings',
      'manage_storage_settings',
      'manage_company_settings',
      'manage_page_helper',
      'allow_file_extensions',
    ],
    submenu: [
      {
        path: '/email-smtp',
        title: 'EMAIL_SMTP_SETTINGS',
        icon: 'email',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['smtp_settings'],
      },
      {
        path: '/general-settings',
        title: 'GENERAL_SETTINGS',
        icon: 'settings',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['general_settings'],
      },
      {
        path: '/storage-settings',
        title: 'STORAGE_SETTINGS',
        icon: 'storage',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['manage_storage_settings'],
      },
      {
        path: '/page-helper',
        title: 'PAGE_HELPER',
        icon: 'help',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['manage_page_helper'],
      },
      {
        path: 'allow-file-extension',
        title: 'ALLOW_FILE_EXTENSIONS',
        icon: 'extension',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['view_allow_file_extensions'],
      },
      {
        path: 'company-profile',
        title: 'COMPANY_PROFILE',
        icon: 'business',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['manage_company_settings'],
      },
      {
        path: 'document-meta-tag',
        title: 'DOCUMENT_META_TAGS',
        icon: 'label',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['view_document_meta_tags'],
      },
    ],
  },
  {
    path: '',
    title: 'LOGS',
    icon: 'visibility',
    class: 'menu-toggle',
    hasClaims: [
      'view_login_audit_logs',
      'view_error_logs',
    ],
    submenu: [
      {
        path: 'login-audit',
        title: 'LOGIN_AUDITS',
        icon: 'key',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['view_login_audit_logs'],
      },
      {
        path: '/logs',
        title: 'ERROR_LOGS',
        icon: 'error',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['view_error_logs'],
      },
    ],
  },
];
