export const environment = {
  production: true,
  apiUrl: 'http://ouk-dms-api.topdev.co.ke/',
  allowExtesions: [
    {
      type: 'office',
      extentions: ['doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'csv'],
    },
    {
      type: 'pdf',
      extentions: ['pdf'],
    },
    {
      type: 'image',
      extentions: [
        "jpg",
        "jpeg",
        "png",
        "gif",
        "bmp",
        "tiff",
        "tif",
        "svg",
        "webp",
        "ico",
        "heif",
        "heic",
        "avif",
        "apng",
        "jfif",
        "pjpeg",
        "pjp",
        "svgz",
        "wmf",
        "emf",
        "djv",
        "djvu",
        "eps",
        "ps",
        "ai",
        "cdr",
        "indd",
        "idml",
        "psd",
        "tga",
        "dds"
      ],
    },
    {
      type: 'text',
      extentions: ['txt'],
    },
    {
      type: 'audio',
      extentions: [
        '3gp',
        'aa',
        'aac',
        'aax',
        'act',
        'aiff',
        'alac',
        'amr',
        'ape',
        'au',
        'awb',
        'dss',
        'dvf',
        'flac',
        'gsm',
        'iklx',
        'ivs',
        'm4a',
        'm4b',
        'm4p',
        'mmf',
        'mp3',
        'mpc',
        'msv',
        'nmf',
        'ogg',
        'oga',
        'mogg',
        'opus',
        'org',
        'ra',
        'rm',
        'raw',
        'rf64',
        'sln',
        'tta',
        'voc',
        'vox',
        'wav',
        'wma',
        'wv',
      ],
    },
    {
      type: 'video',
      extentions: [
        'webm',
        'flv',
        'vob',
        'ogv',
        'ogg',
        'drc',
        'avi',
        'mts',
        'm2ts',
        'wmv',
        'yuv',
        'viv',
        'mp4',
        'm4p',
        '3pg',
        'f4v',
        'f4a',


      ],
    },
  ],
  chunkSize: 1024 * 1024 * 5
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zonerun`, `zoneDelegateinvokeTask`
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown
 */
// import 'zonejs/plugins/zone-error';  // Included with Angular CLI
